### ISSUE TITLE
Tokens not being passed to subscribeToPayViaDetails via isDestinationPayable

### ISSUE THREAD

**Issue by eNzyOfficial** [alexbosworth/lightning#139]
https://github.com/alexbosworth/lightning/blob/37837f21aaeec005b16fbc549fc706384e5379e7/lnd_methods/offchain/is_destination_payable.js#L59

Can you confirm the above logic is correct?

If I pass in `tokens` it's always null and `subscribeToPayViaDetails` function fails with `ExpectedTokenAmountToPayInPaymentDetails`.

Example:

```
const { lnd } = authenticatedLndGrpc({
  cert,
  macaroon,
  socket
})

const request = 'lnbcrt50u...'

const { destination, tokens } = await decodePaymentRequest({
  request,
  lnd
})

const isPayable = await isDestinationPayable({
  destination,
  tokens,
  lnd
})
```

**Comment by alexbosworth** [comment]
```        
const tokens = !args.mtokens ? null : args.tokens || defaultTokens;
```

> If I pass in tokens

ok this would mean that const tokens would evaluate as args.tokens

is that null?

**Comment by alexbosworth** [comment]
what happens if you use mtokens instead of tokens? it works ok?

**Comment by eNzyOfficial** [comment]
It doesn't, it throws the following:

```
Error: UnexpectedDifferingMtokensAndTokens
    at module.exports (/.../node_modules/lightning/bolt00/payment_amounts.js:71:13)
    at asyncAuto.params (/.../node_modules/lightning/lnd_methods/offchain/subscribe_to_pay.js:352:23)
    at runTask (/.../node_modules/async/auto.js:293:13)
    at /.../node_modules/async/auto.js:233:31
    at processQueue (/.../node_modules/async/auto.js:243:13)
    at taskComplete (/.../node_modules/async/auto.js:259:9)
    at /.../node_modules/async/auto.js:286:17
    at /.../node_modules/async/internal/onlyOnce.js:12:16
    at asyncAuto.maxCltvDelta (/.../node_modules/lightning/lnd_methods/offchain/subscribe_to_pay.js:331:16)
    at runTask (/.../node_modules/async/auto.js:293:13)
```

**Comment by alexbosworth** [comment]
I mean if you use the mtokens and tokens together like pass both that you get from decodePaymentRequest

**Comment by eNzyOfficial** [comment]
Same thing for me:

```
const { lnd } = authenticatedLndGrpc({
  cert,
  macaroon,
  socket
})

const request = 'lnbcrt50u...'

const { destination, tokens } = await decodePaymentRequest({
  request,
  lnd
})

const isPayable = await isDestinationPayable({
  destination,
  tokens,
  mtokens: tokens,
  lnd
})
```

**Comment by alexbosworth** [comment]
sorry i mean decodePaymentRequest will return mtokens as well as tokens

so

```node
const { destination, mtokens } = await decodePaymentRequest({
```

```node
const isPayable = await isDestinationPayable({
  destination,
  mtokens,
  lnd
})
```

**Comment by eNzyOfficial** [comment]
If I use only `mtokens`

I'm still getting `UnexpectedDifferingMtokensAndTokens`

inside `payment_amounts.js` I add `console.log(tokensAsMtokens, args.mtokens)` which returns `1000 500000`

if I include both `mtokens` and `tokens` in the initial call, it works fine.

```
const { destination, tokens, mtokens } = await decodePaymentRequest({
    request,
    lnd
})

const isPayable = await isDestinationPayable({
    destination,
    mtokens,
    tokens,
    lnd
})
```

**Comment by alexbosworth** [comment]
should be corrected now
