### ISSUE TITLE
Legacy address support for `getChainFeeEstimate` function

### ISSUE THREAD

**Issue by vindard** [alexbosworth/lightning#52]
Just double-checking, is there support for legacy addresses with this function?

I tried calling it with `1lhuauzvup3wvkn4ptgcsqwxqknswujqnw` and got back the error:
```
err: [
    503,
    "UnexpectedErrEstimatingFeeForChainSend",
    {
    "err": {
        "code": 2,
        "details": "decoded address is of unknown format",
        "metadata": {
        "content-type": [
            "application/grpc"
        ]
        }
    }
    }
]

```

**Comment by alexbosworth** [comment]
Yeah it supports it, something looks weird about that address in that it has no uppercase

**Comment by vindard** [comment]
That's it thanks! Just noticed we were lowercase-ing these

**Comment by vindard** [comment]
Hey, I changed our lower-casing and was just doing some testing on this again. I'm getting a few errors with different address types.

**Legacy (p2pkh)**
```
DEBUG address: 1KxEAbSNHzod8N4hMVUnxuFP36M7pj6436
DEBUG 'send_to' ARG: [ { address: '1KxEAbSNHzod8N4hMVUnxuFP36M7pj6436', tokens: 5000 } ]
DEBUG 'getChainFeeEstimate' Error: [
  503,
  'UnexpectedErrEstimatingFeeForChainSend',
  {
    err: Error: 2 UNKNOWN: unknown address type
        at Object.callErrorFromStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/call.ts:81:24)
        at Object.onReceiveStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/client.ts:343:36)
        at Object.onReceiveStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
        at Object.onReceiveStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
        at node_modules/lightning/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      code: 2,
      details: 'unknown address type',
      metadata: [Metadata]
    }
  }
]
```

**p2sh**
```
DEBUG address: 3A8MMfbBesZiUVMpuCoC82thFVcKaMYZwM
DEBUG 'send_to' ARG: [ { address: '3A8MMfbBesZiUVMpuCoC82thFVcKaMYZwM', tokens: 5000 } ]
DEBUG 'getChainFeeEstimate' Error: [
  503,
  'UnexpectedErrEstimatingFeeForChainSend',
  {
    err: Error: 2 UNKNOWN: unknown address type
        at Object.callErrorFromStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/call.ts:81:24)
        at Object.onReceiveStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/client.ts:343:36)
        at Object.onReceiveStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
        at Object.onReceiveStatus (node_modules/lightning/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
        at node_modules/lightning/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      code: 2,
      details: 'unknown address type',
      metadata: [Metadata]
    }
  }
]
```

---

Works perfectly with Native Segwit (p2wpkh). It may be that I'm doing something silly here, but I can't figure out what so far.
```
DEBUG address: bc1q7lxaue6nj2qftd8glakx0umtzgzr9ughds5u4z
DEBUG 'send_to' ARG: [
  {
    address: 'bc1q7lxaue6nj2qftd8glakx0umtzgzr9ughds5u4z',
    tokens: 5000
  }
]
DEBUG 'getOnChainFee' return: 9050
```

**Comment by alexbosworth** [comment]
The LND that is calling is also a mainnet LND?

**Comment by vindard** [comment]
It's regtest, there's my silly mistake.

But are native segwit addresses a valid testnet address format?

**Comment by alexbosworth** [comment]
> But are native segwit addresses a valid testnet address format?

Potentially the LND level validation is not extended to bech32 network checking because that works differently and btc wallet is fairly old compared to LND
