### ISSUE TITLE
Unimplemented error when trying to make payments

### ISSUE THREAD

**Issue by 2624789** [alexbosworth/lightning#56]
Hi, I am trying to make a payment (`payViaPaymentRequest`) using a btcpay server deployed on lunanode with a self signed certificate and I am getting `UnexpectedPaymentError`.

This is the code that is rising the error:

```
	try {
		payment = await payViaPaymentRequest({
		  	lnd,
	  		request: paymentData.request,
		});
	} catch (e) {
		console.error(e);
		return res.status(500).send({ error: 'Payment failed' });
	}
```
and this is the error:

```
        [
	  503,
	  'UnexpectedPaymentError',
	  {
	    err: Error: 12 UNIMPLEMENTED: 
	        at Object.callErrorFromStatus (/code/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
	        at Object.onReceiveStatus (/code/node_modules/@grpc/grpc-js/build/src/client.js:331:49)
	        at Object.onReceiveStatus (/code/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
	        at /code/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
	        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
	      code: 12,
	      details: '',
	      metadata: [Metadata]
	    }
	  }
	]
```

If I try to get payments (`getPayments`) or get and create invoices (`getInvoices`, `createInvoice`) it works

**Comment by alexbosworth** [comment]
what version of LND?

**Comment by 2624789** [comment]
I'm using lightning@5.3.4

**Comment by 2624789** [comment]
I get almost the same error.

Code:
```
  let response;
  try {
    response = await getWalletVersion({
      lnd,
    });
  } catch (e) {
    console.error(e);
    return res.status(500).send({ error: 'error' });
  }
  console.log(response)
```

Error:
```
[
  503,
  'UnexpectedGetWalletVersion',
  {
    err: Error: 12 UNIMPLEMENTED: 
        at Object.callErrorFromStatus (/code/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/code/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
        at Object.onReceiveStatus (/code/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
        at Object.onReceiveStatus (/code/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
        at /code/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      code: 12,
      details: '',
      metadata: [Metadata]
    }
  }
]
```

**Comment by alexbosworth** [comment]
OK I think the issue is you need to update your LND?

**Comment by 2624789** [comment]
Do you know which version should I be using for it to work?

**Comment by alexbosworth** [comment]
At least `v0.11.0-beta` is required and it's also a good idea to run this version or higher due to security issues with older releases

The latest version of LND is `0.14.1`

**Comment by 2624789** [comment]
This is the one that I'm using `lnd version 0.14.1-beta commit=basedon-v0.14.1-beta-fresh-btcpay`

**Comment by alexbosworth** [comment]
This commit seems to be inconsistent with the regular commit hash, possibly it was built without RPC support? I would inquire with btcpay

**Comment by 2624789** [comment]
Ok. I'll do that and come back to close/update the issue. Thanks!
